### ISSUE TITLE
Is showing and filtering by "category", "rating", "star-rating" or "actor"(s) possible?

### ISSUE THREAD

**Issue by Krupek20** [tomzox/nxtvepg#3]
Hi,

I am trying to use nxtvepg with source https://epg.ovh/plar.gz.

It contains entries like:
`<programme start="20230531210000 +0200" stop="20230531231000 +0200" channel="HBO">
    <title lang="pl">Shazam! Gniew bogów</title>
    <desc lang="pl">Mijają dwa lata od czasu...</desc>
    <credits>
      <director>David F. Sandberg</director>
      <actor>Shazam - Zachary Levi</actor>
      <actor>Mary Bromfield - Grace Caroline Currey</actor>
    </credits>
    <date>2022</date>
    <category lang="pl">Komedia Przygodowa</category>
    <icon src="https://ptv-prod.wpcdn.pl/media/akpa5186289.jpg" />
    <country lang="pl">USA</country>
    <rating>
      <value>12+</value>
    </rating>
    <star-rating>
      <value>4/10</value>
    </star-rating>
  </programme>`

Is it possible to display "category", "rating", "star-rating" or "actor"(s) on the main screen grid?
Is it possible to filter by these columns to show programmes of specified category only or of specified rating/start-raging or with specified actor?

Note that category is in Polish not English (so "Komedia Przygodowa" means "Adventure Comedy"). I'm not sure if Polish makes some extra problem for nxtvepg implementation.

My ultimate scenario would be to filter the displayed programmes to e.g. only comedies with some specified actor and with rating greater than specified value. Is it possible?

One more problem (I can extract it to separate issue if needed) - I am not able to search in nxtvepg using Polish diacritics like "ó" or "ą" etc... so I am not able to find title like "bogów" or description like "Mijają" (see my example programme above).

**Comment by tomzox** [comment]
Some adaption was required to support this provider well. I uploaded a debug release 3.0.2 to https://nxtvepg.sourceforge.net/pre-releases.html:

1. Added parser support for Polish parental rating system
2. Added Polish language support for theme category mapping.
3. Adapted editorial (star) rating parser to accept fractional values.

Star-rating should already have worked, just some ratings like "6.8 / 10" were not accepted (IMHO use of fractional values does not comply with xmltv.dtd; formally correct would be 68 / 100). Note nxtvepg refers to this attribute as "editorial rating". XMLTV "rating" is referred-to as "parental rating". It didn't work before as the format "12+" etc. was not understood by the parser yet.

nxtvepg doesn't support categories fully as XMLTV does. nxtvepg will try to map XMLTV categories to an internal table, from which you then can select in the filter menus. I tried to add a Polish mapping table, please review: https://github.com/tomzox/nxtvepg/blob/master/xmltv/xmltv_themes.c (it maps to the table shown in https://github.com/tomzox/nxtvepg/blob/master/epgui/pdc_themes.c). Currently the mapping will produce only one theme code, although the database would support up to 7 per programme.

Searching for "bogów" or "Mijają" works fine for me (when copying the text via CTRL-C and CTRL-V from firefox into the entry field of nxtvepg dialog "Filter - Text search": It find the programme entry you quoted. Could you please provide more details what steps you do and how the outcome differs from what you would expect? Note the actor list is merged into the description by nxtvepg, so normal text search will find actor's names.

A problem I can't solve short term is that nxtvepg is limited to 254 channels (due to using a very compact database format; the project started 1998, when my PC had only 64MB of RAM ;-) but your provider lists more than 500. Only data from the first 254 channels will be loaded.

**Comment by Krupek20** [comment]
Per Windows Defender I get a SEVERE warning that:
  https://nxtvepg.sourceforge.net/tmp/nxtvepg-3.0.2-win.zip\
has a virus:
  Trojan:Win32/Wacatac.H!ml - This program is dangerous and executes commands from an attacker.

file: .\nxtvepg-3.0.2-win.zip->nxtvepg.exe
file: .\nxtvepg-3.0.2-win.zip->nxtvepgd.exe

webfile: .\nxtvepg-3.0.2-win.zip|https://nxtvepg.sourceforge.net/tmp/nxtvepg-3.0.2-win.zip

**Comment by tomzox** [comment]
Unfortunately I didn't keep a local copy of the 3.0.2 snapshot, so I can't tell if someone messed with it. I'm pretty sure my GNU mingw cross-compiler on Linux does not inject Windows viruses into generated executables. Let's just try again: I uploaded a new version 3.0.3 to the same location. In this one the limitation to 254 channels is newly removed. (Performance improvements for such huge databases still pending.) MD5 sum of ZIP file nxtvepg-3.0.3-win.zip is 7bf0df879d22d6654a4aa14a11fa8d56.

In the mean time I also found that there is actually a bug in text search: Case insensitive search won't work correctly. This bug was introduced in release 3.0.0 when switching from Latin-1 to UTF-8 for internal encoding. Therefore, search currently only works correctly while option "Match case" is checked.

I just realized what you probably meant with your original first question "Is it possible to display "category", "rating", "star-rating" or "actor"(s) on the main screen grid?": To add editorial or parental rating value as a column in the overview table, click on the little symbol to the left of all column headers (i.e. left of "Day in default configuration). In the dialog that opens, select "Editorial rating" et.al. in the list on the left then press button "Add". You can also add user-defined columns, e.g. for programmes where selected actors starred. Showing the actor list in the overview list is not supported, as there is not enough space.

**Comment by tomzox** [comment]
Closing, as OP is no longer responsive.

The reported issues should be fixed in release 3.1.0. If not, please feel encouraged to raise a new "issue".
